### ISSUE TITLE
Review categories in https://github.com/shannaniggans/cyberanode/blob/main/2.%20categories.md and consolidate and move to this repository

### ISSUE THREAD

**Issue by shannaniggans** [CyberAnode/Registrations#4]

**Comment by shannaniggans** [comment]
[categories.md](categories.md) created here and products and services categories updated. As these will be tags on the website, @barnie995, can you confirm if we can have '&' symbols in the tags or we are better to write 'and'.

@thequietlife do you want to update descriptions as needed to make them clear and in general just make the page read better?

**Comment by barnie995** [comment]
@shannaniggans  & is fine and I dont see any issues with it.  These tags will ultimately be front matter on the site, so adding it in shouldnt cause unnecessary issues.

**Comment by thequietlife** [comment]
@shannaniggans I don't have any changes sorry. It looks pretty good
